### ISSUE TITLE
Broken link in Readme

### ISSUE THREAD

**Issue by g2rant** [mautic/plugin-helloworld#6]
The readme mentions "This can be used as an example in combination with the Integrations plugin wiki," but the link (https://github.com/mautic-inc/plugin-integrations/wiki) leads to a 404. Any way of getting that back or updated?

**Comment by kuzmany** [comment]
Documention was moved to https://developer.mautic.org/#integration-framework

But from my experiences this plugin with commented code is the best to learn how to use it.
